// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PucPocVS.Models;

#nullable disable

namespace PucPocVS.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20261006000515_M2AdicionandoTabelas-Errata")]
    partial class M2AdicionandoTabelasErrata
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("PucPocVS.Models.Anotacao", b =>
                {
                    b.Property<int>("IdAnotacao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdAnotacao"));

                    b.Property<string>("AnotacaoMentorado")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("IdMentorado")
                        .HasColumnType("int");

                    b.Property<int>("IdMentoria")
                        .HasColumnType("int");

                    b.HasKey("IdAnotacao");

                    b.HasIndex("IdMentorado");

                    b.HasIndex("IdMentoria");

                    b.ToTable("Anotacoes");
                });

            modelBuilder.Entity("PucPocVS.Models.AreaConhecimento", b =>
                {
                    b.Property<int>("IdArea")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdArea"));

                    b.Property<string>("Nome")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdArea");

                    b.ToTable("AreasConhecimento");

                    b.HasData(
                        new
                        {
                            IdArea = 1,
                            Nome = "Backend"
                        },
                        new
                        {
                            IdArea = 2,
                            Nome = "Frontend"
                        },
                        new
                        {
                            IdArea = 3,
                            Nome = "Data Science"
                        },
                        new
                        {
                            IdArea = 4,
                            Nome = "Mobile"
                        },
                        new
                        {
                            IdArea = 5,
                            Nome = "Fullstack"
                        },
                        new
                        {
                            IdArea = 6,
                            Nome = "Cyber Security"
                        });
                });

            modelBuilder.Entity("PucPocVS.Models.AvaliacaoMaterial", b =>
                {
                    b.Property<int>("IdAvaliacaoMaterial")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdAvaliacaoMaterial"));

                    b.Property<string>("Comentario")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("IdMaterialApoio")
                        .HasColumnType("int");

                    b.Property<int>("IdMentorado")
                        .HasColumnType("int");

                    b.Property<float>("Nota")
                        .HasColumnType("real");

                    b.HasKey("IdAvaliacaoMaterial");

                    b.HasIndex("IdMaterialApoio");

                    b.HasIndex("IdMentorado");

                    b.ToTable("AvaliacoesMaterial");
                });

            modelBuilder.Entity("PucPocVS.Models.AvaliacaoMentor", b =>
                {
                    b.Property<int>("IdAvaliacaoMentor")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdAvaliacaoMentor"));

                    b.Property<string>("Comentario")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("IdMentor")
                        .HasColumnType("int");

                    b.Property<int>("IdMentorado")
                        .HasColumnType("int");

                    b.Property<int>("IdMentoria")
                        .HasColumnType("int");

                    b.Property<float>("Nota")
                        .HasColumnType("real");

                    b.HasKey("IdAvaliacaoMentor");

                    b.HasIndex("IdMentor");

                    b.HasIndex("IdMentorado");

                    b.HasIndex("IdMentoria");

                    b.ToTable("AvaliacoesMentor");
                });

            modelBuilder.Entity("PucPocVS.Models.AvaliacaoMentoria", b =>
                {
                    b.Property<int>("IdAvaliacaoMentoria")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdAvaliacaoMentoria"));

                    b.Property<string>("Comentario")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("IdMentorado")
                        .HasColumnType("int");

                    b.Property<int>("IdMentoria")
                        .HasColumnType("int");

                    b.Property<float>("Nota")
                        .HasColumnType("real");

                    b.HasKey("IdAvaliacaoMentoria");

                    b.HasIndex("IdMentorado");

                    b.HasIndex("IdMentoria");

                    b.ToTable("AvaliacoesMentoria");
                });

            modelBuilder.Entity("PucPocVS.Models.Disponibilidade", b =>
                {
                    b.Property<int>("IdDisponibilidade")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdDisponibilidade"));

                    b.Property<bool>("Disponivel")
                        .HasColumnType("bit");

                    b.Property<DateTime>("HoraInicio")
                        .HasColumnType("datetime2");

                    b.Property<int>("IdDuracao")
                        .HasColumnType("int");

                    b.Property<int>("IdMentor")
                        .HasColumnType("int");

                    b.HasKey("IdDisponibilidade");

                    b.HasIndex("IdDuracao");

                    b.HasIndex("IdMentor");

                    b.ToTable("Disponibilidades");
                });

            modelBuilder.Entity("PucPocVS.Models.Duracao", b =>
                {
                    b.Property<int>("IdDuracao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdDuracao"));

                    b.Property<int>("Tempo")
                        .HasColumnType("int");

                    b.HasKey("IdDuracao");

                    b.ToTable("Duracoes");
                });

            modelBuilder.Entity("PucPocVS.Models.MaterialDeApoio", b =>
                {
                    b.Property<int>("IdMaterialApoio")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdMaterialApoio"));

                    b.Property<int>("IdMentor")
                        .HasColumnType("int");

                    b.Property<int>("IdMentoria")
                        .HasColumnType("int");

                    b.Property<string>("Material")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Titulo")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdMaterialApoio");

                    b.HasIndex("IdMentor");

                    b.HasIndex("IdMentoria");

                    b.ToTable("MateriaisDeApoio");
                });

            modelBuilder.Entity("PucPocVS.Models.Mentor", b =>
                {
                    b.Property<int>("IdUsuario")
                        .HasColumnType("int");

                    b.HasKey("IdUsuario");

                    b.ToTable("Mentores");

                    b.HasData(
                        new
                        {
                            IdUsuario = 1
                        },
                        new
                        {
                            IdUsuario = 2
                        },
                        new
                        {
                            IdUsuario = 3
                        },
                        new
                        {
                            IdUsuario = 4
                        },
                        new
                        {
                            IdUsuario = 5
                        },
                        new
                        {
                            IdUsuario = 6
                        },
                        new
                        {
                            IdUsuario = 7
                        },
                        new
                        {
                            IdUsuario = 8
                        },
                        new
                        {
                            IdUsuario = 9
                        },
                        new
                        {
                            IdUsuario = 10
                        },
                        new
                        {
                            IdUsuario = 11
                        },
                        new
                        {
                            IdUsuario = 12
                        },
                        new
                        {
                            IdUsuario = 13
                        },
                        new
                        {
                            IdUsuario = 14
                        },
                        new
                        {
                            IdUsuario = 15
                        },
                        new
                        {
                            IdUsuario = 16
                        },
                        new
                        {
                            IdUsuario = 17
                        },
                        new
                        {
                            IdUsuario = 18
                        },
                        new
                        {
                            IdUsuario = 19
                        },
                        new
                        {
                            IdUsuario = 20
                        });
                });

            modelBuilder.Entity("PucPocVS.Models.MentorAreas", b =>
                {
                    b.Property<int>("IdMentorArea")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdMentorArea"));

                    b.Property<int>("IdArea")
                        .HasColumnType("int");

                    b.Property<int>("IdMentor")
                        .HasColumnType("int");

                    b.HasKey("IdMentorArea");

                    b.HasIndex("IdArea");

                    b.HasIndex("IdMentor");

                    b.ToTable("MentoresAreas");

                    b.HasData(
                        new
                        {
                            IdMentorArea = 1,
                            IdArea = 1,
                            IdMentor = 1
                        },
                        new
                        {
                            IdMentorArea = 2,
                            IdArea = 2,
                            IdMentor = 2
                        },
                        new
                        {
                            IdMentorArea = 3,
                            IdArea = 5,
                            IdMentor = 3
                        },
                        new
                        {
                            IdMentorArea = 4,
                            IdArea = 2,
                            IdMentor = 4
                        },
                        new
                        {
                            IdMentorArea = 5,
                            IdArea = 3,
                            IdMentor = 5
                        },
                        new
                        {
                            IdMentorArea = 6,
                            IdArea = 1,
                            IdMentor = 6
                        },
                        new
                        {
                            IdMentorArea = 7,
                            IdArea = 4,
                            IdMentor = 7
                        },
                        new
                        {
                            IdMentorArea = 8,
                            IdArea = 5,
                            IdMentor = 8
                        },
                        new
                        {
                            IdMentorArea = 9,
                            IdArea = 1,
                            IdMentor = 9
                        },
                        new
                        {
                            IdMentorArea = 10,
                            IdArea = 6,
                            IdMentor = 10
                        },
                        new
                        {
                            IdMentorArea = 11,
                            IdArea = 4,
                            IdMentor = 11
                        },
                        new
                        {
                            IdMentorArea = 12,
                            IdArea = 2,
                            IdMentor = 12
                        },
                        new
                        {
                            IdMentorArea = 13,
                            IdArea = 1,
                            IdMentor = 13
                        },
                        new
                        {
                            IdMentorArea = 14,
                            IdArea = 3,
                            IdMentor = 14
                        },
                        new
                        {
                            IdMentorArea = 15,
                            IdArea = 6,
                            IdMentor = 15
                        },
                        new
                        {
                            IdMentorArea = 16,
                            IdArea = 5,
                            IdMentor = 16
                        },
                        new
                        {
                            IdMentorArea = 17,
                            IdArea = 3,
                            IdMentor = 17
                        },
                        new
                        {
                            IdMentorArea = 18,
                            IdArea = 4,
                            IdMentor = 18
                        },
                        new
                        {
                            IdMentorArea = 19,
                            IdArea = 1,
                            IdMentor = 19
                        },
                        new
                        {
                            IdMentorArea = 20,
                            IdArea = 2,
                            IdMentor = 20
                        },
                        new
                        {
                            IdMentorArea = 21,
                            IdArea = 1,
                            IdMentor = 3
                        },
                        new
                        {
                            IdMentorArea = 22,
                            IdArea = 2,
                            IdMentor = 8
                        });
                });

            modelBuilder.Entity("PucPocVS.Models.MentorTecnologia", b =>
                {
                    b.Property<int>("IdMentorTecnologia")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdMentorTecnologia"));

                    b.Property<int>("IdMentor")
                        .HasColumnType("int");

                    b.Property<int>("IdTecnologia")
                        .HasColumnType("int");

                    b.HasKey("IdMentorTecnologia");

                    b.HasIndex("IdMentor");

                    b.HasIndex("IdTecnologia");

                    b.ToTable("MentoresTecnologias");

                    b.HasData(
                        new
                        {
                            IdMentorTecnologia = 1,
                            IdMentor = 1,
                            IdTecnologia = 6
                        },
                        new
                        {
                            IdMentorTecnologia = 2,
                            IdMentor = 1,
                            IdTecnologia = 2
                        },
                        new
                        {
                            IdMentorTecnologia = 3,
                            IdMentor = 6,
                            IdTecnologia = 1
                        },
                        new
                        {
                            IdMentorTecnologia = 4,
                            IdMentor = 9,
                            IdTecnologia = 6
                        },
                        new
                        {
                            IdMentorTecnologia = 5,
                            IdMentor = 2,
                            IdTecnologia = 3
                        },
                        new
                        {
                            IdMentorTecnologia = 6,
                            IdMentor = 2,
                            IdTecnologia = 4
                        },
                        new
                        {
                            IdMentorTecnologia = 7,
                            IdMentor = 2,
                            IdTecnologia = 5
                        },
                        new
                        {
                            IdMentorTecnologia = 8,
                            IdMentor = 4,
                            IdTecnologia = 5
                        },
                        new
                        {
                            IdMentorTecnologia = 9,
                            IdMentor = 3,
                            IdTecnologia = 6
                        },
                        new
                        {
                            IdMentorTecnologia = 10,
                            IdMentor = 3,
                            IdTecnologia = 5
                        },
                        new
                        {
                            IdMentorTecnologia = 11,
                            IdMentor = 8,
                            IdTecnologia = 1
                        },
                        new
                        {
                            IdMentorTecnologia = 12,
                            IdMentor = 8,
                            IdTecnologia = 5
                        },
                        new
                        {
                            IdMentorTecnologia = 13,
                            IdMentor = 5,
                            IdTecnologia = 1
                        },
                        new
                        {
                            IdMentorTecnologia = 14,
                            IdMentor = 5,
                            IdTecnologia = 2
                        },
                        new
                        {
                            IdMentorTecnologia = 15,
                            IdMentor = 10,
                            IdTecnologia = 1
                        },
                        new
                        {
                            IdMentorTecnologia = 16,
                            IdMentor = 7,
                            IdTecnologia = 11
                        },
                        new
                        {
                            IdMentorTecnologia = 17,
                            IdMentor = 6,
                            IdTecnologia = 9
                        },
                        new
                        {
                            IdMentorTecnologia = 18,
                            IdMentor = 11,
                            IdTecnologia = 11
                        },
                        new
                        {
                            IdMentorTecnologia = 19,
                            IdMentor = 12,
                            IdTecnologia = 3
                        },
                        new
                        {
                            IdMentorTecnologia = 20,
                            IdMentor = 13,
                            IdTecnologia = 6
                        },
                        new
                        {
                            IdMentorTecnologia = 21,
                            IdMentor = 14,
                            IdTecnologia = 1
                        },
                        new
                        {
                            IdMentorTecnologia = 22,
                            IdMentor = 15,
                            IdTecnologia = 10
                        },
                        new
                        {
                            IdMentorTecnologia = 23,
                            IdMentor = 16,
                            IdTecnologia = 5
                        },
                        new
                        {
                            IdMentorTecnologia = 24,
                            IdMentor = 17,
                            IdTecnologia = 12
                        },
                        new
                        {
                            IdMentorTecnologia = 25,
                            IdMentor = 18,
                            IdTecnologia = 7
                        },
                        new
                        {
                            IdMentorTecnologia = 26,
                            IdMentor = 19,
                            IdTecnologia = 8
                        },
                        new
                        {
                            IdMentorTecnologia = 27,
                            IdMentor = 20,
                            IdTecnologia = 3
                        },
                        new
                        {
                            IdMentorTecnologia = 28,
                            IdMentor = 11,
                            IdTecnologia = 7
                        },
                        new
                        {
                            IdMentorTecnologia = 29,
                            IdMentor = 7,
                            IdTecnologia = 7
                        },
                        new
                        {
                            IdMentorTecnologia = 30,
                            IdMentor = 9,
                            IdTecnologia = 13
                        },
                        new
                        {
                            IdMentorTecnologia = 31,
                            IdMentor = 10,
                            IdTecnologia = 12
                        },
                        new
                        {
                            IdMentorTecnologia = 32,
                            IdMentor = 12,
                            IdTecnologia = 4
                        },
                        new
                        {
                            IdMentorTecnologia = 33,
                            IdMentor = 13,
                            IdTecnologia = 8
                        },
                        new
                        {
                            IdMentorTecnologia = 34,
                            IdMentor = 14,
                            IdTecnologia = 2
                        },
                        new
                        {
                            IdMentorTecnologia = 35,
                            IdMentor = 15,
                            IdTecnologia = 9
                        },
                        new
                        {
                            IdMentorTecnologia = 36,
                            IdMentor = 16,
                            IdTecnologia = 13
                        },
                        new
                        {
                            IdMentorTecnologia = 37,
                            IdMentor = 17,
                            IdTecnologia = 2
                        },
                        new
                        {
                            IdMentorTecnologia = 38,
                            IdMentor = 18,
                            IdTecnologia = 5
                        },
                        new
                        {
                            IdMentorTecnologia = 39,
                            IdMentor = 19,
                            IdTecnologia = 13
                        },
                        new
                        {
                            IdMentorTecnologia = 40,
                            IdMentor = 20,
                            IdTecnologia = 4
                        },
                        new
                        {
                            IdMentorTecnologia = 41,
                            IdMentor = 4,
                            IdTecnologia = 3
                        },
                        new
                        {
                            IdMentorTecnologia = 42,
                            IdMentor = 20,
                            IdTecnologia = 5
                        },
                        new
                        {
                            IdMentorTecnologia = 43,
                            IdMentor = 12,
                            IdTecnologia = 5
                        },
                        new
                        {
                            IdMentorTecnologia = 44,
                            IdMentor = 14,
                            IdTecnologia = 12
                        },
                        new
                        {
                            IdMentorTecnologia = 45,
                            IdMentor = 10,
                            IdTecnologia = 2
                        },
                        new
                        {
                            IdMentorTecnologia = 46,
                            IdMentor = 8,
                            IdTecnologia = 13
                        });
                });

            modelBuilder.Entity("PucPocVS.Models.Mentorado", b =>
                {
                    b.Property<int>("IdUsuario")
                        .HasColumnType("int");

                    b.Property<string>("AreaInteresse")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdUsuario");

                    b.ToTable("Mentorados");

                    b.HasData(
                        new
                        {
                            IdUsuario = 1,
                            AreaInteresse = "Backend"
                        },
                        new
                        {
                            IdUsuario = 2,
                            AreaInteresse = "Frontend"
                        },
                        new
                        {
                            IdUsuario = 3,
                            AreaInteresse = "DevOps"
                        },
                        new
                        {
                            IdUsuario = 4,
                            AreaInteresse = "UX/UI Design"
                        },
                        new
                        {
                            IdUsuario = 5,
                            AreaInteresse = "Data Science"
                        },
                        new
                        {
                            IdUsuario = 6,
                            AreaInteresse = "Mobile iOS"
                        },
                        new
                        {
                            IdUsuario = 7,
                            AreaInteresse = "Mobile Android"
                        },
                        new
                        {
                            IdUsuario = 8,
                            AreaInteresse = "Gestão de Projetos"
                        },
                        new
                        {
                            IdUsuario = 9,
                            AreaInteresse = "Backend"
                        },
                        new
                        {
                            IdUsuario = 10,
                            AreaInteresse = "Cloud Computing"
                        },
                        new
                        {
                            IdUsuario = 11,
                            AreaInteresse = "Frontend"
                        },
                        new
                        {
                            IdUsuario = 12,
                            AreaInteresse = "Engenharia de Dados"
                        },
                        new
                        {
                            IdUsuario = 13,
                            AreaInteresse = "Arquitetura de Software"
                        },
                        new
                        {
                            IdUsuario = 14,
                            AreaInteresse = "UX/UI Design"
                        },
                        new
                        {
                            IdUsuario = 15,
                            AreaInteresse = "Segurança da Informação"
                        },
                        new
                        {
                            IdUsuario = 16,
                            AreaInteresse = "QA e Testes"
                        },
                        new
                        {
                            IdUsuario = 17,
                            AreaInteresse = "Inteligência Artificial"
                        },
                        new
                        {
                            IdUsuario = 18,
                            AreaInteresse = "Marketing Digital"
                        },
                        new
                        {
                            IdUsuario = 19,
                            AreaInteresse = "DevOps"
                        },
                        new
                        {
                            IdUsuario = 20,
                            AreaInteresse = "Product Management"
                        });
                });

            modelBuilder.Entity("PucPocVS.Models.Mentoria", b =>
                {
                    b.Property<int>("IdMentoria")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdMentoria"));

                    b.Property<string>("Descricao")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("HoraInicio")
                        .HasColumnType("datetime2");

                    b.Property<int>("IdMentor")
                        .HasColumnType("int");

                    b.Property<int>("IdMentorado")
                        .HasColumnType("int");

                    b.Property<string>("Link")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdMentoria");

                    b.HasIndex("IdMentor");

                    b.HasIndex("IdMentorado");

                    b.ToTable("Mentorias");
                });

            modelBuilder.Entity("PucPocVS.Models.NivelAcesso", b =>
                {
                    b.Property<int>("IdNivelAcesso")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdNivelAcesso"));

                    b.Property<string>("Descricao")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdNivelAcesso");

                    b.ToTable("NiveisAcesso");

                    b.HasData(
                        new
                        {
                            IdNivelAcesso = 1,
                            Descricao = "Administrador"
                        },
                        new
                        {
                            IdNivelAcesso = 2,
                            Descricao = "Mentor"
                        },
                        new
                        {
                            IdNivelAcesso = 3,
                            Descricao = "Mentorado"
                        });
                });

            modelBuilder.Entity("PucPocVS.Models.Tecnologia", b =>
                {
                    b.Property<int>("IdTecnologia")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdTecnologia"));

                    b.Property<string>("Nome")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdTecnologia");

                    b.ToTable("Tecnologias");

                    b.HasData(
                        new
                        {
                            IdTecnologia = 1,
                            Nome = "Python"
                        },
                        new
                        {
                            IdTecnologia = 2,
                            Nome = "SQL"
                        },
                        new
                        {
                            IdTecnologia = 3,
                            Nome = "HTML"
                        },
                        new
                        {
                            IdTecnologia = 4,
                            Nome = "CSS"
                        },
                        new
                        {
                            IdTecnologia = 5,
                            Nome = "JavaScript"
                        },
                        new
                        {
                            IdTecnologia = 6,
                            Nome = "C#"
                        },
                        new
                        {
                            IdTecnologia = 7,
                            Nome = "Java"
                        },
                        new
                        {
                            IdTecnologia = 8,
                            Nome = "C++"
                        },
                        new
                        {
                            IdTecnologia = 9,
                            Nome = "Go"
                        },
                        new
                        {
                            IdTecnologia = 10,
                            Nome = "Rust"
                        },
                        new
                        {
                            IdTecnologia = 11,
                            Nome = "Swift"
                        },
                        new
                        {
                            IdTecnologia = 12,
                            Nome = "R"
                        },
                        new
                        {
                            IdTecnologia = 13,
                            Nome = "PHP"
                        });
                });

            modelBuilder.Entity("PucPocVS.Models.Usuario", b =>
                {
                    b.Property<int>("IdUsuario")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdUsuario"));

                    b.Property<string>("AtivoArea")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataNasc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Escolaridade")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("char(2)");

                    b.Property<int>("IdNivelAcesso")
                        .HasColumnType("int");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PerfilAtivo")
                        .HasColumnType("bit");

                    b.Property<string>("Senha")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdUsuario");

                    b.HasIndex("IdNivelAcesso");

                    b.ToTable("Usuarios");

                    b.HasData(
                        new
                        {
                            IdUsuario = 1,
                            AtivoArea = "Sim",
                            DataCriacao = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DataNasc = new DateTime(1990, 5, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "carlos@email.com",
                            Escolaridade = "PG",
                            IdNivelAcesso = 2,
                            Nome = "Carlos Silva",
                            PerfilAtivo = true,
                            Senha = "SenhaPadrao123"
                        },
                        new
                        {
                            IdUsuario = 2,
                            AtivoArea = "Sim",
                            DataCriacao = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DataNasc = new DateTime(1990, 5, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "mariana@email.com",
                            Escolaridade = "ES",
                            IdNivelAcesso = 2,
                            Nome = "Mariana Souza",
                            PerfilAtivo = true,
                            Senha = "SenhaPadrao123"
                        },
                        new
                        {
                            IdUsuario = 3,
                            AtivoArea = "Sim",
                            DataCriacao = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DataNasc = new DateTime(1990, 5, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "roberto@email.com",
                            Escolaridade = "ME",
                            IdNivelAcesso = 2,
                            Nome = "Roberto Alves",
                            PerfilAtivo = true,
                            Senha = "SenhaPadrao123"
                        },
                        new
                        {
                            IdUsuario = 4,
                            AtivoArea = "Sim",
                            DataCriacao = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DataNasc = new DateTime(1990, 5, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "ana@email.com",
                            Escolaridade = "ES",
                            IdNivelAcesso = 2,
                            Nome = "Ana Clara",
                            PerfilAtivo = true,
                            Senha = "SenhaPadrao123"
                        },
                        new
                        {
                            IdUsuario = 5,
                            AtivoArea = "Sim",
                            DataCriacao = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DataNasc = new DateTime(1990, 5, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "lucas@email.com",
                            Escolaridade = "DO",
                            IdNivelAcesso = 2,
                            Nome = "Lucas Mendes",
                            PerfilAtivo = true,
                            Senha = "SenhaPadrao123"
                        },
                        new
                        {
                            IdUsuario = 6,
                            AtivoArea = "Sim",
                            DataCriacao = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DataNasc = new DateTime(1990, 5, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "beatriz@email.com",
                            Escolaridade = "PG",
                            IdNivelAcesso = 2,
                            Nome = "Beatriz Costa",
                            PerfilAtivo = true,
                            Senha = "SenhaPadrao123"
                        },
                        new
                        {
                            IdUsuario = 7,
                            AtivoArea = "Sim",
                            DataCriacao = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DataNasc = new DateTime(1990, 5, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "fernando@email.com",
                            Escolaridade = "ES",
                            IdNivelAcesso = 2,
                            Nome = "Fernando Gomes",
                            PerfilAtivo = true,
                            Senha = "SenhaPadrao123"
                        },
                        new
                        {
                            IdUsuario = 8,
                            AtivoArea = "Sim",
                            DataCriacao = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DataNasc = new DateTime(1990, 5, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "camila@email.com",
                            Escolaridade = "ME",
                            IdNivelAcesso = 2,
                            Nome = "Camila Rocha",
                            PerfilAtivo = true,
                            Senha = "SenhaPadrao123"
                        },
                        new
                        {
                            IdUsuario = 9,
                            AtivoArea = "Sim",
                            DataCriacao = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DataNasc = new DateTime(1990, 5, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "rafael@email.com",
                            Escolaridade = "ES",
                            IdNivelAcesso = 2,
                            Nome = "Rafael Lima",
                            PerfilAtivo = true,
                            Senha = "SenhaPadrao123"
                        },
                        new
                        {
                            IdUsuario = 10,
                            AtivoArea = "Sim",
                            DataCriacao = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DataNasc = new DateTime(1990, 5, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "juliana@email.com",
                            Escolaridade = "PG",
                            IdNivelAcesso = 2,
                            Nome = "Juliana Pinto",
                            PerfilAtivo = true,
                            Senha = "SenhaPadrao123"
                        },
                        new
                        {
                            IdUsuario = 11,
                            AtivoArea = "Sim",
                            DataCriacao = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DataNasc = new DateTime(1990, 5, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "diego@email.com",
                            Escolaridade = "ES",
                            IdNivelAcesso = 2,
                            Nome = "Diego Martins",
                            PerfilAtivo = true,
                            Senha = "SenhaPadrao123"
                        },
                        new
                        {
                            IdUsuario = 12,
                            AtivoArea = "Sim",
                            DataCriacao = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DataNasc = new DateTime(1990, 5, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "patricia@email.com",
                            Escolaridade = "ME",
                            IdNivelAcesso = 2,
                            Nome = "Patricia Dias",
                            PerfilAtivo = true,
                            Senha = "SenhaPadrao123"
                        },
                        new
                        {
                            IdUsuario = 13,
                            AtivoArea = "Sim",
                            DataCriacao = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DataNasc = new DateTime(1990, 5, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "gustavo@email.com",
                            Escolaridade = "DO",
                            IdNivelAcesso = 2,
                            Nome = "Gustavo Reis",
                            PerfilAtivo = true,
                            Senha = "SenhaPadrao123"
                        },
                        new
                        {
                            IdUsuario = 14,
                            AtivoArea = "Sim",
                            DataCriacao = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DataNasc = new DateTime(1990, 5, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "leticia@email.com",
                            Escolaridade = "ES",
                            IdNivelAcesso = 2,
                            Nome = "Leticia Oliveira",
                            PerfilAtivo = true,
                            Senha = "SenhaPadrao123"
                        },
                        new
                        {
                            IdUsuario = 15,
                            AtivoArea = "Sim",
                            DataCriacao = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DataNasc = new DateTime(1990, 5, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "thiago@email.com",
                            Escolaridade = "PG",
                            IdNivelAcesso = 2,
                            Nome = "Thiago Carvalho",
                            PerfilAtivo = true,
                            Senha = "SenhaPadrao123"
                        },
                        new
                        {
                            IdUsuario = 16,
                            AtivoArea = "Sim",
                            DataCriacao = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DataNasc = new DateTime(1990, 5, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "amanda@email.com",
                            Escolaridade = "ES",
                            IdNivelAcesso = 2,
                            Nome = "Amanda Farias",
                            PerfilAtivo = true,
                            Senha = "SenhaPadrao123"
                        },
                        new
                        {
                            IdUsuario = 17,
                            AtivoArea = "Sim",
                            DataCriacao = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DataNasc = new DateTime(1990, 5, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "rodrigo@email.com",
                            Escolaridade = "ME",
                            IdNivelAcesso = 2,
                            Nome = "Rodrigo Nunes",
                            PerfilAtivo = true,
                            Senha = "SenhaPadrao123"
                        },
                        new
                        {
                            IdUsuario = 18,
                            AtivoArea = "Sim",
                            DataCriacao = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DataNasc = new DateTime(1990, 5, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "fernanda@email.com",
                            Escolaridade = "ES",
                            IdNivelAcesso = 2,
                            Nome = "Fernanda Barros",
                            PerfilAtivo = true,
                            Senha = "SenhaPadrao123"
                        },
                        new
                        {
                            IdUsuario = 19,
                            AtivoArea = "Sim",
                            DataCriacao = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DataNasc = new DateTime(1990, 5, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "marcelo@email.com",
                            Escolaridade = "PG",
                            IdNivelAcesso = 2,
                            Nome = "Marcelo Moraes",
                            PerfilAtivo = true,
                            Senha = "SenhaPadrao123"
                        },
                        new
                        {
                            IdUsuario = 20,
                            AtivoArea = "Sim",
                            DataCriacao = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DataNasc = new DateTime(1990, 5, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "carolina@email.com",
                            Escolaridade = "ES",
                            IdNivelAcesso = 2,
                            Nome = "Carolina Azevedo",
                            PerfilAtivo = true,
                            Senha = "SenhaPadrao123"
                        });
                });

            modelBuilder.Entity("PucPocVS.Models.Anotacao", b =>
                {
                    b.HasOne("PucPocVS.Models.Mentorado", "Mentorado")
                        .WithMany()
                        .HasForeignKey("IdMentorado")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PucPocVS.Models.Mentoria", "Mentoria")
                        .WithMany("Anotacoes")
                        .HasForeignKey("IdMentoria")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Mentorado");

                    b.Navigation("Mentoria");
                });

            modelBuilder.Entity("PucPocVS.Models.AvaliacaoMaterial", b =>
                {
                    b.HasOne("PucPocVS.Models.MaterialDeApoio", "MaterialDeApoio")
                        .WithMany("AvaliacoesMateriais")
                        .HasForeignKey("IdMaterialApoio")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PucPocVS.Models.Mentorado", "Mentorado")
                        .WithMany("AvaliacoesMaterial")
                        .HasForeignKey("IdMentorado")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("MaterialDeApoio");

                    b.Navigation("Mentorado");
                });

            modelBuilder.Entity("PucPocVS.Models.AvaliacaoMentor", b =>
                {
                    b.HasOne("PucPocVS.Models.Mentor", "Mentor")
                        .WithMany("AvaliacoesMentores")
                        .HasForeignKey("IdMentor")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PucPocVS.Models.Mentorado", "Mentorado")
                        .WithMany("AvaliacoesMentor")
                        .HasForeignKey("IdMentorado")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PucPocVS.Models.Mentoria", "Mentoria")
                        .WithMany("AvaliacoesMentor")
                        .HasForeignKey("IdMentoria")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Mentor");

                    b.Navigation("Mentorado");

                    b.Navigation("Mentoria");
                });

            modelBuilder.Entity("PucPocVS.Models.AvaliacaoMentoria", b =>
                {
                    b.HasOne("PucPocVS.Models.Mentorado", "Mentorado")
                        .WithMany("AvaliacoesMentoria")
                        .HasForeignKey("IdMentorado")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PucPocVS.Models.Mentoria", "Mentoria")
                        .WithMany("AvaliacoesMentoria")
                        .HasForeignKey("IdMentoria")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Mentorado");

                    b.Navigation("Mentoria");
                });

            modelBuilder.Entity("PucPocVS.Models.Disponibilidade", b =>
                {
                    b.HasOne("PucPocVS.Models.Duracao", "Duracao")
                        .WithMany()
                        .HasForeignKey("IdDuracao")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PucPocVS.Models.Mentor", "Mentor")
                        .WithMany("Disponibilidades")
                        .HasForeignKey("IdMentor")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Duracao");

                    b.Navigation("Mentor");
                });

            modelBuilder.Entity("PucPocVS.Models.MaterialDeApoio", b =>
                {
                    b.HasOne("PucPocVS.Models.Mentor", "Mentor")
                        .WithMany()
                        .HasForeignKey("IdMentor")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PucPocVS.Models.Mentoria", "Mentoria")
                        .WithMany("MateriaisApoio")
                        .HasForeignKey("IdMentoria")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Mentor");

                    b.Navigation("Mentoria");
                });

            modelBuilder.Entity("PucPocVS.Models.Mentor", b =>
                {
                    b.HasOne("PucPocVS.Models.Usuario", "Usuario")
                        .WithOne("Mentor")
                        .HasForeignKey("PucPocVS.Models.Mentor", "IdUsuario")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("PucPocVS.Models.MentorAreas", b =>
                {
                    b.HasOne("PucPocVS.Models.AreaConhecimento", "AreaConhecimento")
                        .WithMany("MentorAreas")
                        .HasForeignKey("IdArea")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PucPocVS.Models.Mentor", "Mentor")
                        .WithMany("MentorAreas")
                        .HasForeignKey("IdMentor")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("AreaConhecimento");

                    b.Navigation("Mentor");
                });

            modelBuilder.Entity("PucPocVS.Models.MentorTecnologia", b =>
                {
                    b.HasOne("PucPocVS.Models.Mentor", "Mentor")
                        .WithMany("MentorTecnologias")
                        .HasForeignKey("IdMentor")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PucPocVS.Models.Tecnologia", "Tecnologia")
                        .WithMany("MentorTecnologias")
                        .HasForeignKey("IdTecnologia")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Mentor");

                    b.Navigation("Tecnologia");
                });

            modelBuilder.Entity("PucPocVS.Models.Mentorado", b =>
                {
                    b.HasOne("PucPocVS.Models.Usuario", "Usuario")
                        .WithOne("Mentorado")
                        .HasForeignKey("PucPocVS.Models.Mentorado", "IdUsuario")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("PucPocVS.Models.Mentoria", b =>
                {
                    b.HasOne("PucPocVS.Models.Mentor", "Mentor")
                        .WithMany()
                        .HasForeignKey("IdMentor")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PucPocVS.Models.Mentorado", "Mentorado")
                        .WithMany()
                        .HasForeignKey("IdMentorado")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Mentor");

                    b.Navigation("Mentorado");
                });

            modelBuilder.Entity("PucPocVS.Models.Usuario", b =>
                {
                    b.HasOne("PucPocVS.Models.NivelAcesso", "NivelAcesso")
                        .WithMany()
                        .HasForeignKey("IdNivelAcesso")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("NivelAcesso");
                });

            modelBuilder.Entity("PucPocVS.Models.AreaConhecimento", b =>
                {
                    b.Navigation("MentorAreas");
                });

            modelBuilder.Entity("PucPocVS.Models.MaterialDeApoio", b =>
                {
                    b.Navigation("AvaliacoesMateriais");
                });

            modelBuilder.Entity("PucPocVS.Models.Mentor", b =>
                {
                    b.Navigation("AvaliacoesMentores");

                    b.Navigation("Disponibilidades");

                    b.Navigation("MentorAreas");

                    b.Navigation("MentorTecnologias");
                });

            modelBuilder.Entity("PucPocVS.Models.Mentorado", b =>
                {
                    b.Navigation("AvaliacoesMaterial");

                    b.Navigation("AvaliacoesMentor");

                    b.Navigation("AvaliacoesMentoria");
                });

            modelBuilder.Entity("PucPocVS.Models.Mentoria", b =>
                {
                    b.Navigation("Anotacoes");

                    b.Navigation("AvaliacoesMentor");

                    b.Navigation("AvaliacoesMentoria");

                    b.Navigation("MateriaisApoio");
                });

            modelBuilder.Entity("PucPocVS.Models.Tecnologia", b =>
                {
                    b.Navigation("MentorTecnologias");
                });

            modelBuilder.Entity("PucPocVS.Models.Usuario", b =>
                {
                    b.Navigation("Mentor");

                    b.Navigation("Mentorado");
                });
#pragma warning restore 612, 618
        }
    }
}
